{"pageProps":{"posts":[{"date":"2021-02-22T13:03:57+09:00","description":"envが原因でした","slug":"flask-python-dotenv-errors","title":"Flaskでpython-dotenvを利用する際のcan't open file '/home/$USERNAME/app.py'","tags":["python","env","python-dotenv","error","flask"]}],"tag":"env"},"__N_SSG":true}